sudo: required
dist: trusty
language: node_js
node_js:
    - '8'
install:
    - npm install
script:
    - npm test
before_script:
    - npm run testrpc > /dev/null &
        - sleep 5
# after_script:
    #- npm run coverage && cat coverage/lcov.info | coveralls
